routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.post.index');
// });

Auth::routes(['register' => false]);

// frontend
Route::get('/404', function(){
	return view('frontend.errors.404');
})->name('error.404');

Route::get('/', [App\Http\Controllers\Frontend\PostController::class, 'index'])->name('post.index');
Route::get('/pages/{slug}', [App\Http\Controllers\Frontend\PageController::class, 'show'])->name('page.show');
Route::get('/category/{id}', [App\Http\Controllers\Frontend\CategoryController::class, 'show'])->name('category.show');
Route::post('/newsletter', [App\Http\Controllers\Frontend\NewsletterController::class, 'store'])->name('newsletter.store');
Route::resource('/author', App\Http\Controllers\Frontend\AuthorController::class, ['names' => 'author'])->only('index', 'show');
Route::resource('/contact-us', App\Http\Controllers\Frontend\ContactUsController::class, ['names' => 'contact'])->only('index', 'store');
Route::post('/comment', [App\Http\Controllers\Frontend\CommentController::class, 'store'])->name('comment.store');

// backend
Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'middleware' => ['auth']], function (){
	Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('index');
	Route::resource('/posts', App\Http\Controllers\Backend\PostController::class, ['names' => 'post'])->except('show');
	Route::post('/posts/upload', [App\Http\Controllers\Backend\PostController::class, 'upload'])->name('post.upload');
	Route::resource('/categories', App\Http\Controllers\Backend\CategoryController::class, ['names' => 'category'])->except('create', 'edit', 'show');
	Route::resource('/message', App\Http\Controllers\Backend\MessageController::class, ['names' => 'message'])->only('index', 'destroy');
	Route::resource('/newsletter', App\Http\Controllers\Backend\NewsletterController::class, ['names' => 'newsletter'])->only('index', 'destroy');
	Route::resource('/comment', App\Http\Controllers\Backend\CommentController::class, ['names' => 'comment']);
	Route::post('/comment/reply', [App\Http\Controllers\Backend\CommentController::class, 'reply'])->name('comment.reply');
	Route::resource('/role', App\Http\Controllers\Backend\RoleController::class, ['names' => 'role'])->except('create', 'edit', 'show');
	Route::resource('/user', App\Http\Controllers\Backend\UserController::class, ['names' => 'user'])->except('create', 'edit', 'show');
	Route::put('/reset-password/{id}', [App\Http\Controllers\Backend\UserController::class, 'resetPassword'])->name('user.reset-password');
	Route::put('/setting/change-password', [App\Http\Controllers\Backend\SettingController::class, 'changePassword'])->name('setting.change-password');
	Route::resource('/setting', App\Http\Controllers\Backend\SettingController::class, ['names' => 'setting'])->only('index', 'update');
	Route::resource('/pages', App\Http\Controllers\Backend\PageController::class, ['names' => 'page']);

	Route::get('/404', function(){
		return view('backend.errors.404');
	})->name('error.404');
});

// post
Route::get('/{slug}', [App\Http\Controllers\Frontend\PostController::class, 'show'])->name('post.show');

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view categories', ['only' => ['index']]);
        $this->middleware('permission:create categories', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit categories', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete categories', ['only' => ['destroy']]);
    }

    public function index()
    {
        $categories = Category::orderByDesc('created_at')->get();
        return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['name' => 'required|unique:categories,name']);
        $category = Category::create(['name' => strip_tags($request->name)]);
        if ($category) {
            return redirect()->back()->with('success', 'category '.$category->name.' saved successfully');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        if ($category) {
            $request->validate(['name' => 'required|unique:categories,name,'.$category->id]);
            $upd = $category->update(['name' => strip_tags($request->name)]);
            if ($upd) {
                return redirect()->back()->with('success', 'category '.$category->name.' updated successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if ($category) {
            $delete = $category->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'category '.$category->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view comments', ['only' => ['index']]);
        $this->middleware('permission:reply comments', ['only' => ['reply']]);
        $this->middleware('permission:delete comments', ['only' => ['destroy']]);
    }

    public function index()
    {
        $comments = Comment::has('post')->with('post', 'childrens.parent')->whereNull("parent_id")->orderByDesc('created_at')->get();
        return view('backend.comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);
        if ($comment) {
            $delete = $comment->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'comment '.$comment->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }

    public function reply(Request $request)
    {
        $request->validate([
            'post_id'   => 'required|exists:posts,id',
            'parent_id' => 'required|exists:comments,id',
            'reply_to'  => 'required|exists:comments,id',
            'comment'   => 'required'
        ]);
        $user = auth()->user();
        $payloads = $request->except('_token');
        $payloads = removeHtmlTagsOfFields($payloads);
        $payloads['name']  = $user->name;
        $payloads['email'] = $user->email;
        $comment = Comment::create($payloads);
        if ($comment) {
            return redirect()->back()->with('success', 'comment '.$comment->name.' reply successfully');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
	public function index()
	{
		$visits = DB::table('shetabit_visits')->where('method', 'GET')->whereBetween('created_at', [date("Y-m-d H:i:s", strtotime("-7 days")), date("Y-m-d H:i:s")])->get()->groupBy(function($item) {
			return date('Y-m-d', strtotime($item->created_at));
		});
		$count_posts = Post::where('type', 1)->count();
		$count_views = DB::table('shetabit_visits')->where('method', 'GET');
		$top_posts   = DB::select("SELECT p.title, COUNT(slug) as total FROM posts p INNER JOIN shetabit_visits v ON v.url LIKE CONCAT('%/', p.slug) GROUP BY slug ORDER BY total DESC limit 5;");
		return view('backend.dashboard', compact('visits', 'count_posts', 'count_views', 'top_posts'));
	}
}

app/Http/Controllers/Backend/MessageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ContactUs;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view messages', ['only' => ['index']]);
        $this->middleware('permission:delete messages', ['only' => ['destroy']]);
    }

    public function index()
    {
        $messages = ContactUs::orderByDesc('created_at')->get();
        return view('backend.messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = ContactUs::find($id);
        if ($message) {
            $delete = $message->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'message '.$message->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/NewsletterController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Newsletter;

class NewsletterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view newsletters', ['only' => ['index']]);
        $this->middleware('permission:delete newsletters', ['only' => ['destroy']]);
    }

    public function index()
    {
        $newsletters = Newsletter::orderByDesc('created_at')->get();
        return view('backend.newsletters.index', compact('newsletters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $newsletter = Newsletter::find($id);
        if ($newsletter) {
            $delete = $newsletter->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'newsletter '.$newsletter->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

resources/views/backend/roles/index.blade.php
@extends('layouts.backend')
@section('title', 'AdminLTE 3 | Role Index')
@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/backend/datatable.css')}}">
<style type="text/css">
	#tbl-posts_paginate, #tbl-posts_filter{
		float: right;
	}
	.list-roles{
		-webkit-column-count: 3;
		-moz-column-count: 3;
		column-count: 3;
		list-style-type: none;
	}
</style>
@endsection
@section('content')
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-12">
				<div class="card">
					<div class="card-header">
						@can('create roles')
						<button type="button" onclick="$('#modal-create').modal('show')" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Create</button>
						&nbsp;&nbsp;&nbsp;&nbsp;
						@endcan
						<h3 class="card-title float-right">DataTable Roles</h3>
					</div>
					<div class="card-body">
						<table id="tbl-role" class="table table-bordered table-hover dataTable">
							<thead>
								<th width="5%">No</th>
								<th>Role</th>
								<th>Permission</th>
								@canany(['edit roles', 'delete roles'])
								<th width="5%">Action</th>
								@endcan
							</thead>
							<tbody>
								@foreach($roles as $role)
								<tr>
									<td>{{$loop->iteration}}</td>
									<td>{{$role->name}}</td>
									@if($role->permissions->count() > 0)
									<td>
										@php
										$items = [];
										foreach ($nameRoles as $nameRole) {
											$items[$nameRole] = $role->permissions->map(function($item) use ($nameRole){
												if (Str::contains(strtolower($item->name), strtolower($nameRole))) {
													return ucwords($item->name);
												} 
											})->filter()->all();
										}
										$items = array_filter($items);
										@endphp
										<ul style="padding-left: 15px;list-style-type: none;">
											@foreach($items as $name => $item)
											<li class="mt-2">
												<span class="text-primary">{{$name}}</span>
												<br>
												@foreach($item as $v)
												<span class="badge badge-secondary mr-2 mt-2 p-1">{{ucwords($v)}}</span>
												@endforeach
											</li>
											@endforeach
										</ul>
									</td>
									@else
									<td><center><i>No Item</i></center></td>
									@endif
									@canany(['edit roles', 'delete roles'])
									<td class="text-nowrap">
										<button class="btn btn-sm btn-warning" data-id="{{$role->id}}" data-title="{{$role->name}}" data-roles="{{$role->permissions->pluck('name')->toJson()}}" onclick="modalEdit(this)" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-edit"></i></button>
										&nbsp;&nbsp;
										<button class="btn btn-sm btn-danger" data-id="{{$role->id}}" data-title="{{$role->name}}" onclick="modalDelete(this)" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-trash"></i></button>
									</td>
									@endcan
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

@can('create roles')
<div class="modal fade" id="modal-create" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form method="POST" action="{{route('dashboard.role.store')}}">
				@csrf
				<div class="modal-header bg-primary">
					<h4 class="modal-title">Create Role</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Permissions</label>
						<br>
						<ul style="list-style-type: none;">
							@foreach($permissionsroles as $name => $permissionsrole)
							<li class="border-top py-2">
								<b>{{$name}}</b>
								<ul class="list-roles">
									@foreach($permissionsrole as $permission)
									<li>
										<div class="form-check">
											<label class="form-check-label"><input class="form-check-input" data-role="{{strtolower($name)}}" onclick="setPermissions(this)" type="checkbox" name="permissions[]" value="{{strtolower($permission)}}"> {{ucwords($permission)}}</label>
										</div>
									</li>
									@endforeach
								</ul>
							</li>
							@endforeach
						</ul>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('edit roles')
<div class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('PUT')
				<div class="modal-header bg-warning">
					<h4 class="modal-title">Edit role</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Permissions</label>
						<br>
						<ul style="list-style-type: none;">
							@foreach($permissionsroles as $name => $permissionsrole)
							<li class="border-top py-2">
								<b>{{$name}}</b>
								<ul class="list-roles">
									@foreach($permissionsrole as $permission)
									<li>
										<div class="form-check">
											<label class="form-check-label"><input class="form-check-input" data-role="{{strtolower($name)}}" onclick="setPermissions(this)" type="checkbox" name="permissions[]" value="{{strtolower($permission)}}"> {{ucwords($permission)}}</label>
										</div>
									</li>
									@endforeach
								</ul>
							</li>
							@endforeach
						</ul>
					</div>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-warning">Upadte</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('delete roles')
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('DELETE')
				<div class="modal-header bg-danger">
					<h4 class="modal-title">Delete role</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Are you sure delete role <b id="modal-delete-role"></b></p>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-danger">Delete</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@endsection
@section('js')
<script type="text/javascript" src="{{asset('js/backend/datatable.js')}}"></script>
<script type="text/javascript">
	$(document).ready( function () {
		$('#tbl-role').DataTable();
	});

	$("#modal-create, #modal-edit").find("form").submit(function(){
		if ($(this).find('input:checkbox').filter(':checked').length < 1){
			alert("Please Check at least one Check Box");
			return false;
		}else{
			$(this).find('input:checkbox').removeAttr('disabled');
		}
	});

	@can('edit roles')
	function modalEdit(self)
	{
		var id    = $(self).attr('data-id');
		var roles = $(self).attr('data-roles');
		var modal = $('#modal-edit');
		var url   = '{{ route("dashboard.role.update", ":id") }}';
		url = url.replace(':id', id);
		roles = JSON.parse(roles);
		roles.forEach(function(name){
			modal.find('input[type="checkbox"][value="'+name+'"]').prop('checked', 'checked');
		});
		modal.find('input[type="checkbox"][value*="view"]:checked').each(function(){
			var role = $(this).data('role');
			if (modal.find('input[type="checkbox"][data-role="'+role+'"][value!="view '+role+'"]:checked').length < 1) {
				modal.find('input[type="checkbox"][value="view '+role+'"]').removeAttr('disabled');
			}else{
				modal.find('input[type="checkbox"][value="view '+role+'"]').attr('disabled', true);		
			}
		});
		modal.find('form').attr('action', url);
		modal.find('input[name="name"]').val($(self).attr('data-title'));
		modal.modal('show');
	}
	@endcan

	@can('delete roles')
	function modalDelete(self)
	{
		var id    = $(self).attr('data-id');
		var modal = $('#modal-delete');
		var url   = '{{ route("dashboard.role.destroy", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.find('#modal-delete-role').html('('+$(self).attr('data-title')+')');
		modal.modal('show');
	}
	@endcan
	
	function setPermissions(self)
	{
		var value = $(self).val();
		var role  = $(self).data('role');
		var modal = $(self).parents('.modal');
		if ($(self).is(":checked")) {
			if (!value.includes('view')) {
				modal.find('input[type="checkbox"][value="view '+role+'"]').attr('disabled', true);
				modal.find('input[type="checkbox"][value="view '+role+'"]').prop('checked', 'checked');
			}
		}else{
			if (modal.find('input[type="checkbox"][data-role="'+role+'"]:not(:disabled)').filter(':checked').length < 1) {
				modal.find('input[type="checkbox"][value="view '+role+'"]').removeAttr('disabled');
			}
		}
	}
</script>
@endsection