routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.post.index');
// });

Auth::routes(['register' => false]);

// frontend
Route::get('/404', function(){
	return view('frontend.errors.404');
})->name('error.404');

Route::get('/', [App\Http\Controllers\Frontend\PostController::class, 'index'])->name('post.index');
Route::get('/pages/{slug}', [App\Http\Controllers\Frontend\PageController::class, 'show'])->name('page.show');
Route::get('/category/{id}', [App\Http\Controllers\Frontend\CategoryController::class, 'show'])->name('category.show');
Route::post('/newsletter', [App\Http\Controllers\Frontend\NewsletterController::class, 'store'])->name('newsletter.store');
Route::resource('/author', App\Http\Controllers\Frontend\AuthorController::class, ['names' => 'author'])->only('index', 'show');
Route::resource('/contact-us', App\Http\Controllers\Frontend\ContactUsController::class, ['names' => 'contact'])->only('index', 'store');
Route::post('/comment', [App\Http\Controllers\Frontend\CommentController::class, 'store'])->name('comment.store');

// backend
Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'middleware' => ['auth']], function (){
	Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('index');
	Route::resource('/posts', App\Http\Controllers\Backend\PostController::class, ['names' => 'post'])->except('show');
	Route::post('/posts/upload', [App\Http\Controllers\Backend\PostController::class, 'upload'])->name('post.upload');
	Route::resource('/categories', App\Http\Controllers\Backend\CategoryController::class, ['names' => 'category'])->except('create', 'edit', 'show');
	Route::resource('/message', App\Http\Controllers\Backend\MessageController::class, ['names' => 'message'])->only('index', 'destroy');
	Route::resource('/newsletter', App\Http\Controllers\Backend\NewsletterController::class, ['names' => 'newsletter'])->only('index', 'destroy');
	Route::resource('/comment', App\Http\Controllers\Backend\CommentController::class, ['names' => 'comment']);
	Route::post('/comment/reply', [App\Http\Controllers\Backend\CommentController::class, 'reply'])->name('comment.reply');
	Route::resource('/role', App\Http\Controllers\Backend\RoleController::class, ['names' => 'role'])->except('create', 'edit', 'show');
	Route::resource('/user', App\Http\Controllers\Backend\UserController::class, ['names' => 'user'])->except('create', 'edit', 'show');
	Route::put('/reset-password/{id}', [App\Http\Controllers\Backend\UserController::class, 'resetPassword'])->name('user.reset-password');
	Route::put('/setting/change-password', [App\Http\Controllers\Backend\SettingController::class, 'changePassword'])->name('setting.change-password');
	Route::resource('/setting', App\Http\Controllers\Backend\SettingController::class, ['names' => 'setting'])->only('index', 'update');
	Route::resource('/pages', App\Http\Controllers\Backend\PageController::class, ['names' => 'page']);

	Route::get('/404', function(){
		return view('backend.errors.404');
	})->name('error.404');
});

// post
Route::get('/{slug}', [App\Http\Controllers\Frontend\PostController::class, 'show'])->name('post.show');

app/Http/Controllers/Frontend/AuthorController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\user;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authors = User::orderBy('name')->get();
        return view('frontend.authors.index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $author = User::where('id', $id)->first();
        if ($author) {
            $posts = $author->posts()->where([['type', '=', 1], ['published_at', '<=', date('Y-m-d H:i:s')]])->orderByDesc('created_at')->paginate(10);
            return view('frontend.posts.index', compact('posts', 'author'));
        }
        return redirect()->route('error.404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/CategoryController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::with('posts')->where('id', $id)->first();
        if ($category) {
            $posts = $category->posts()->where([['type', '=', 1], ['published_at', '<=', date('Y-m-d H:i:s')]])->orderByDesc('published_at')->paginate(10);
            return view('frontend.posts.index', compact('posts'));
        }
        return redirect()->route('error.404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/CommentController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    => 'required',
            'email'   => 'required|email',
            'comment' => 'required',
            'post_id' => 'required|exists:posts,id'
        ]);
        $payloads = $request->except('_token');
        $payloads = removeHtmlTagsOfFields($payloads);
        $comment  = Comment::create($payloads);
        if ($comment) {
            return redirect()->back()->with('success', 'Comment successfully');
        }
        return redirect()->back()->with('success', 'Comment failed');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/ContactUsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ContactUs;

class ContactUsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.pages.contact');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $request->validate([
            'name'    => 'required|min:4',
            'email'   => 'required|email',
            'phone'   => 'nullable|numeric|digits_between:8,15',
            'subject' => 'required',
            'message' => 'required',
        ]);

        $payloads = $request->except('_token');
        $payloads = removeHtmlTagsOfFields($payloads);
        $message  = ContactUs::create($payloads);
        if ($message) {
            return redirect()->back()->with('success', 'successfully, Thank You');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/NewsletterController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Newsletter;

class NewsletterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'email' => 'required|email'
        ]);
        $save = Newsletter::firstOrCreate(['email' => strip_tags($request->email)]);
        if ($save) {
            return redirect()->back()->with('success', 'successfully, Thank You');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/PageController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;

class PageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $page = Post::where([['type', 2], ['slug', $slug], ['published_at', '<=', date('Y-m-d H:i:s')]])->first();
        if ($page) {
            return view('frontend.pages.show', compact('page'));
        }
        return redirect()->route('error.404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/frontend/partials/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif
  
@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif
   
@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif
   
@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif
  
@if ($errors->any())
<div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    Please check the form below for errors
    <ul>
        @foreach($errors->all() as $error)
        <li>{{$error}}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/frontend/partials/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="widget">
                    <div class="footer-text text-left">
                        <a href="index.html"><img src="images/version/tech-footer-logo.png" alt="" class="img-fluid"></a>
                        <p>Tech Blog is a technology blog, we sharing marketing, news and gadget articles.</p>
                        <div class="social">
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>              
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                        </div>
                        <hr class="invis">
                        <div class="newsletter-widget text-left">
                            <form class="form-inline" method="POST" action="{{route('newsletter.store')}}">
                                @csrf
                                <input type="email" class="form-control" placeholder="Enter your email address" name="email" autocomplete="off" required>
                                <button type="submit" class="btn btn-primary">SUBMIT</button>
                            </form>
                        </div><!-- end newsletter -->
                    </div><!-- end footer-text -->
                </div><!-- end widget -->
            </div><!-- end col -->

            <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                    <h2 class="widget-title">Popular Categories</h2>
                    <div class="link-widget">
                        <ul>
                            @foreach($side_categories->take(5)->sortBy('name') as $category)
                            <li><a href="{{route('category.show', $category->id)}}">{{ucwords($category->name)}} <span>({{$category->posts->count()}} <small>posts</small>)</span></a></li>
                            @endforeach
                        </ul>
                    </div><!-- end link-widget -->
                </div><!-- end widget -->
            </div><!-- end col -->

            <div class="col-lg-2 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                    <h2 class="widget-title">Pages</h2>
                    <div class="link-widget">
                        <ul>
                            @foreach($side_posts->where('type', 2)->sortBy('title') as $page)
                            <li><a href="{{route('page.show', $page->slug)}}">{{$page->title}}</a></li>
                            @endforeach
                        </ul>
                    </div><!-- end link-widget -->
                </div><!-- end widget -->
            </div><!-- end col -->
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <br>
                <div class="copyright">&copy; Tech Blog. Design: <a href="http://html.design" rel="nofollow">HTML Design</a>.</div>
            </div>
        </div>
    </div>
</footer>
<div class="dmtop">Scroll to Top</div>

resources/views/frontend/partials/navbar.blade.php
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" style="top:5px;">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="tech-index.html"><img src="images/version/tech-logo.png" alt=""></a>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url('/')}}">Home</a>
            </li>
            <li class="nav-item dropdown has-submenu menu-large hidden-md-down hidden-sm-down hidden-xs-down">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">News</a>
                <ul class="dropdown-menu megamenu" aria-labelledby="dropdown01">
                    <li>
                        <div class="container">
                            <div class="mega-menu-content clearfix">
                                <div class="tab">
                                    @foreach($side_categories->take(5)->sortBy('name') as $category)
                                    <button class="tablinks {{$loop->iteration == 1 ? 'active' : ''}}" onclick="openCategory(event, '{{'cat-'.$loop->iteration}}')">{{ucwords($category->name)}}</button>
                                    @endforeach
                                </div>

                                <div class="tab-details clearfix">
                                    @foreach($side_categories->take(5)->sortBy('name') as $category)
                                    <div id="{{"cat-".$loop->iteration}}" class="tabcontent {{$loop->iteration == 1 ? 'active' : ''}}">
                                        <div class="row">
                                            @foreach($category->posts->sortByDesc('views')->take(4) as $post)
                                            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                                                <div class="blog-box">
                                                    <div class="post-media">
                                                        <a href="{{route('post.show', $post->slug)}}" title="">
                                                            <img src="{{asset('images/posts/'.$post->thumbnail)}}" alt="" class="img-fluid">
                                                            <div class="hovereffect">
                                                            </div>
                                                            <span class="menucat">{{$category->name}}</span>
                                                        </a>
                                                    </div>
                                                    <div class="blog-meta">
                                                        <h4><a href="{{route('post.show', $post->slug)}}" title="">{{$post->title}}</a></h4>
                                                    </div>
                                                </div>
                                            </div>
                                            @endforeach
                                        </div>                             
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('author.index')}}">Author</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('contact.index')}}">Contact Us</a>
            </li>
            <li class="nav-item">
                @if (Auth::check())
                <a class="nav-link" href="{{route('dashboard.index')}}">Dashboard</a>
                @else
                <a class="nav-link" href="{{url('/login')}}">Login</a>
                @endif
            </li>
        </ul>
        <ul class="navbar-nav mr-2">
            <form action="{{url('/')}}" method="GET">
                <input type="text" name="q" class="form-control search" autocomplete="off" placeholder="Search...">
            </form>
        </ul>
    </div>
</nav>

resources/views/frontend/partials/sidebar.blade.php
<div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 side-post">
    <div class="sidebar">
        <div class="widget">
            <h2 class="widget-title">Popular Posts</h2>
            <div class="blog-list-widget">
                <div class="list-group">
                    @foreach($side_posts->where('type', 1)->sortByDesc('views')->take(5) as $popular)
                    <a href="{{route('post.show', $popular->slug)}}" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="w-100 justify-content-between">
                            <img src="{{asset("images/posts/".$popular->thumbnail)}}" alt="" class="img-fluid float-left">
                            <h5 class="mb-1">{{$popular->title}}</h5>
                            <small>{{date('d F, Y', strtotime($popular->created_at))}}</small>
                        </div>
                    </a>
                    @endforeach
                </div>
            </div><!-- end blog-list -->
        </div><!-- end widget -->

        <div class="widget">
            <h2 class="widget-title">Recent Reviews</h2>
            <div class="blog-list-widget">
                <div class="list-group">
                    @foreach($side_posts->where('type', 1)->sortByDesc('created_at')->take(3) as $recent)
                    <a href="tech-single.html" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="w-100 justify-content-between">
                            <img src="{{asset("images/posts/tech_blog_02.jpg")}}" alt="" class="img-fluid float-left">
                            <h5 class="mb-1">{{Str::limit($recent->title, 30)}}</h5>
                        </div>
                    </a>
                    @endforeach
                </div>
            </div><!-- end blog-list -->
        </div><!-- end widget -->

        <div class="widget">
            <h2 class="widget-title">Categories</h2>
            <div class="tag-cloud-single">
                @foreach($side_categories as $category)
                <a href="{{route('category.show', $category->id)}}" class="text-white"><span class="mt-2">{{$category->name}}</span></a>
                @endforeach
            </div>
        </div>

        {{-- <div class="widget">
            <h2 class="widget-title">Follow Us</h2>

            <div class="row text-center">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <a href="#" class="social-button facebook-button">
                        <i class="fa fa-facebook"></i>
                        <p>27k</p>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <a href="#" class="social-button twitter-button">
                        <i class="fa fa-twitter"></i>
                        <p>98k</p>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <a href="#" class="social-button google-button">
                        <i class="fa fa-google-plus"></i>
                        <p>17k</p>
                    </a>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                    <a href="#" class="social-button youtube-button">
                        <i class="fa fa-youtube"></i>
                        <p>22k</p>
                    </a>
                </div>
            </div>
        </div> --}}
    </div>
</div>