routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.post.index');
// });

Auth::routes(['register' => false]);

// frontend
Route::get('/404', function(){
	return view('frontend.errors.404');
})->name('error.404');

Route::get('/', [App\Http\Controllers\Frontend\PostController::class, 'index'])->name('post.index');
Route::get('/pages/{slug}', [App\Http\Controllers\Frontend\PageController::class, 'show'])->name('page.show');
Route::get('/category/{id}', [App\Http\Controllers\Frontend\CategoryController::class, 'show'])->name('category.show');
Route::post('/newsletter', [App\Http\Controllers\Frontend\NewsletterController::class, 'store'])->name('newsletter.store');
Route::resource('/author', App\Http\Controllers\Frontend\AuthorController::class, ['names' => 'author'])->only('index', 'show');
Route::resource('/contact-us', App\Http\Controllers\Frontend\ContactUsController::class, ['names' => 'contact'])->only('index', 'store');
Route::post('/comment', [App\Http\Controllers\Frontend\CommentController::class, 'store'])->name('comment.store');

// backend
Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'middleware' => ['auth']], function (){
	Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('index');
	Route::resource('/posts', App\Http\Controllers\Backend\PostController::class, ['names' => 'post'])->except('show');
	Route::post('/posts/upload', [App\Http\Controllers\Backend\PostController::class, 'upload'])->name('post.upload');
	Route::resource('/categories', App\Http\Controllers\Backend\CategoryController::class, ['names' => 'category'])->except('create', 'edit', 'show');
	Route::resource('/message', App\Http\Controllers\Backend\MessageController::class, ['names' => 'message'])->only('index', 'destroy');
	Route::resource('/newsletter', App\Http\Controllers\Backend\NewsletterController::class, ['names' => 'newsletter'])->only('index', 'destroy');
	Route::resource('/comment', App\Http\Controllers\Backend\CommentController::class, ['names' => 'comment']);
	Route::post('/comment/reply', [App\Http\Controllers\Backend\CommentController::class, 'reply'])->name('comment.reply');
	Route::resource('/role', App\Http\Controllers\Backend\RoleController::class, ['names' => 'role'])->except('create', 'edit', 'show');
	Route::resource('/user', App\Http\Controllers\Backend\UserController::class, ['names' => 'user'])->except('create', 'edit', 'show');
	Route::put('/reset-password/{id}', [App\Http\Controllers\Backend\UserController::class, 'resetPassword'])->name('user.reset-password');
	Route::put('/setting/change-password', [App\Http\Controllers\Backend\SettingController::class, 'changePassword'])->name('setting.change-password');
	Route::resource('/setting', App\Http\Controllers\Backend\SettingController::class, ['names' => 'setting'])->only('index', 'update');
	Route::resource('/pages', App\Http\Controllers\Backend\PageController::class, ['names' => 'page']);

	Route::get('/404', function(){
		return view('backend.errors.404');
	})->name('error.404');
});

// post
Route::get('/{slug}', [App\Http\Controllers\Frontend\PostController::class, 'show'])->name('post.show');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use App\Traits\Blameable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, Blameable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'about',
        'created_by',
        'updated_by',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class, 'created_by');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view categories', ['only' => ['index']]);
        $this->middleware('permission:create categories', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit categories', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete categories', ['only' => ['destroy']]);
    }

    public function index()
    {
        $categories = Category::orderByDesc('created_at')->get();
        return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['name' => 'required|unique:categories,name']);
        $category = Category::create(['name' => strip_tags($request->name)]);
        if ($category) {
            return redirect()->back()->with('success', 'category '.$category->name.' saved successfully');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        if ($category) {
            $request->validate(['name' => 'required|unique:categories,name,'.$category->id]);
            $upd = $category->update(['name' => strip_tags($request->name)]);
            if ($upd) {
                return redirect()->back()->with('success', 'category '.$category->name.' updated successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if ($category) {
            $delete = $category->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'category '.$category->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view comments', ['only' => ['index']]);
        $this->middleware('permission:reply comments', ['only' => ['reply']]);
        $this->middleware('permission:delete comments', ['only' => ['destroy']]);
    }

    public function index()
    {
        $comments = Comment::has('post')->with('post', 'childrens.parent')->whereNull("parent_id")->orderByDesc('created_at')->get();
        return view('backend.comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);
        if ($comment) {
            $delete = $comment->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'comment '.$comment->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }

    public function reply(Request $request)
    {
        $request->validate([
            'post_id'   => 'required|exists:posts,id',
            'parent_id' => 'required|exists:comments,id',
            'reply_to'  => 'required|exists:comments,id',
            'comment'   => 'required'
        ]);
        $user = auth()->user();
        $payloads = $request->except('_token');
        $payloads = removeHtmlTagsOfFields($payloads);
        $payloads['name']  = $user->name;
        $payloads['email'] = $user->email;
        $comment = Comment::create($payloads);
        if ($comment) {
            return redirect()->back()->with('success', 'comment '.$comment->name.' reply successfully');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
	public function index()
	{
		$visits = DB::table('shetabit_visits')->where('method', 'GET')->whereBetween('created_at', [date("Y-m-d H:i:s", strtotime("-7 days")), date("Y-m-d H:i:s")])->get()->groupBy(function($item) {
			return date('Y-m-d', strtotime($item->created_at));
		});
		$count_posts = Post::where('type', 1)->count();
		$count_views = DB::table('shetabit_visits')->where('method', 'GET');
		$top_posts   = DB::select("SELECT p.title, COUNT(slug) as total FROM posts p INNER JOIN shetabit_visits v ON v.url LIKE CONCAT('%/', p.slug) GROUP BY slug ORDER BY total DESC limit 5;");
		return view('backend.dashboard', compact('visits', 'count_posts', 'count_views', 'top_posts'));
	}
}

app/Http/Controllers/Backend/MessageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ContactUs;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view messages', ['only' => ['index']]);
        $this->middleware('permission:delete messages', ['only' => ['destroy']]);
    }

    public function index()
    {
        $messages = ContactUs::orderByDesc('created_at')->get();
        return view('backend.messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = ContactUs::find($id);
        if ($message) {
            $delete = $message->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'message '.$message->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/NewsletterController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Newsletter;

class NewsletterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view newsletters', ['only' => ['index']]);
        $this->middleware('permission:delete newsletters', ['only' => ['destroy']]);
    }

    public function index()
    {
        $newsletters = Newsletter::orderByDesc('created_at')->get();
        return view('backend.newsletters.index', compact('newsletters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $newsletter = Newsletter::find($id);
        if ($newsletter) {
            $delete = $newsletter->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'newsletter '.$newsletter->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

resources/views/backend/users/index.blade.php
@extends('layouts.backend')
@section('title', 'AdminLTE 3 | User Index')
@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/backend/datatable.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('css/backend/select2.css')}}">
<style type="text/css">
	#tbl-posts_paginate, #tbl-posts_filter{
		float: right;
	}
	.select2-container--default .select2-selection--single{
		height: 38px;
	}
	.select2-container--default .select2-selection--multiple .select2-selection__choice{
		color:#000;
	}
	.list-permissions{
		-webkit-column-count: 3;
		-moz-column-count: 3;
		column-count: 3;
	}
</style>
@endsection
@section('content')
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-12">
				<div class="card">
					<div class="card-header">
						@can('create users')
						<button type="button" onclick="$('#modal-create').modal('show')" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Create</button>
						&nbsp;&nbsp;&nbsp;&nbsp;
						@endcan
						<h3 class="card-title float-right">DataTable Users</h3>
					</div>
					<div class="card-body">
						<table id="tbl-user" class="table table-bordered table-hover dataTable">
							<thead>
								<th width="5%">No</th>
								<th>User</th>
								<th>Email</th>
								<th>Roles</th>
								@canany(['edit users', 'delete users', 'reset password users'])
								<th width="10%">Action</th>
								@endcan
							</thead>
							<tbody>
								@foreach($users as $user)
								<tr>
									<td>{{$loop->iteration}}</td>
									<td>{{$user->name}}</td>
									<td>{{$user->email}}</td>
									@if($user->roles->count() > 0)
									<td>
										<ul style="padding-left: 15px;">
											@foreach($user->roles as $role)
											<li>
												<b>{{ucwords($role->name)}}</b>:<br> 
												@foreach($role->permissions as $permission)
												<span class="badge badge-secondary mr-2 mt-2 p-1">{{ucwords($permission->name)}}</span>
												@endforeach
											</li>
											@endforeach
										</ul>
									</td>
									@else
									<td><center><i>No Item</i></center></td>
									@endif
									@canany(['edit users', 'delete users', 'reset password users'])
									<td class="text-nowrap">
										@can('edit users')
										<button class="btn btn-xs btn-warning" data-id="{{$user->id}}" data-name="{{$user->name}}" data-email="{{$user->email}}" data-roles="{{$user->roles->pluck('name')->toJson()}}" onclick="modalEdit(this)" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-edit"></i></button>
										&nbsp;
										@endcan
										@can('reset password users')
										<button class="btn btn-xs btn-primary" data-id="{{$user->id}}" data-name="{{$user->name}}" onclick="modalReset(this)"><i class="fa fa-key"></i></button>
										&nbsp;
										@endcan
										@can('delete users')
										<button class="btn btn-xs btn-danger" data-id="{{$user->id}}" data-name="{{$user->name}}" onclick="modalDelete(this)" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-trash"></i></button>
										@endcan
									</td>
									@endcan
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

@can('create users')
<div class="modal fade" id="modal-create" tabindex="-1" user="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form method="POST" action="{{route('dashboard.user.store')}}">
				@csrf
				<div class="modal-header bg-primary">
					<h4 class="modal-title">Create user</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" name="name" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" name="password" minlength="6" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Confirm Password</label>
						<input type="password" minlength="6" name="repassword" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Roles</label>
						<select class="form-control select2" multiple name="roles[]" onchange="getPermission(this)" required>
							@foreach($roles as $role)
							<option value="{{$role->name}}" data-permissions="{{$role->permissions->pluck('name')->toJson()}}">{{ucwords($role->name)}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group d-none" id="form-permissions">
						<label>Permissions</label>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('edit users')
<div class="modal fade" id="modal-edit" tabindex="-1" user="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('PUT')
				<div class="modal-header bg-warning">
					<h4 class="modal-title">Edit user</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" name="name" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Roles</label>
						<select class="form-control select2" multiple name="roles[]" onchange="getPermission(this)" required>
							@foreach($roles as $role)
							<option value="{{$role->name}}" data-permissions="{{$role->permissions->pluck('name')->toJson()}}">{{ucwords($role->name)}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group d-none" id="form-permissions">
						<label>Permissions</label>
					</div>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-warning">Upadte</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('reset password users')
<div class="modal fade" id="modal-reset" tabindex="-1" user="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('PUT')
				<div class="modal-header bg-primary">
					<h4 class="modal-title">Reset Password User</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Password</label>
						<input type="password" name="password" minlength="6" class="form-control" autocomplete="off" required>
					</div>
					<div class="form-group">
						<label>Confirm Password</label>
						<input type="password" name="repassword" minlength="6" class="form-control" autocomplete="off" required>
					</div>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-primary">Upadte</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@can('delete users')
<div class="modal fade" id="modal-delete" tabindex="-1" user="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('DELETE')
				<div class="modal-header bg-danger">
					<h4 class="modal-title">Delete user</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Are you sure delete user <b id="modal-delete-user"></b></p>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-danger">Delete</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan

@endsection
@section('js')
<script type="text/javascript" src="{{asset('js/backend/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('js/backend/select2.js')}}"></script>
<script type="text/javascript">
	$(document).ready( function () {
		$('#tbl-user').DataTable();
		$('.select2').select2();
	});

	function getPermission(self)
	{
		var modal   = $(self).parents('.modal');
		var results = [];
		var data = $(self).find("option:selected");
		if (data.length > 0) {
			data.each(function(el){
				var roles = $(this).data('permissions');
				roles.forEach(function(role){
					results.push(role);
				});
			});
			results  = results.filter(onlyUnique);
			var html = "<ul class='list-permissions'>";
			results.forEach(function(permission){
				html += "<li>"+permission+"</li>"
			});
			html += "</ul";
			modal.find('#form-permissions').removeClass('d-none');
			modal.find('#form-permissions').empty();
			modal.find('#form-permissions').append(html);
		}else{
			modal.find('#form-permissions').addClass('d-none');
			modal.find('ul.list-permissions').remove();
		}
	}

	function onlyUnique(value, index, self) {
		return self.indexOf(value) === index;
	}

	@can('edit users')
	function modalEdit(self)
	{
		var id    = $(self).attr('data-id');
		var name  = $(self).attr('data-name');
		var email = $(self).attr('data-email');
		var roles = JSON.parse($(self).attr('data-roles'));
		var modal = $('#modal-edit');
		var url   = '{{ route("dashboard.user.update", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.find('input[name="name"]').val(name);
		modal.find('input[name="email"]').val(email);
		modal.find('select[name="roles[]"]').val(roles).change();
		modal.modal('show');
	}
	@endcan

	@can('reset password users')
	function modalReset(self)
	{
		var id    = $(self).attr('data-id');
		var name  = $(self).attr('data-name');
		var modal = $('#modal-reset');
		var url   = '{{ route("dashboard.user.reset-password", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.modal('show');
	}
	@endcan

	@can('delete users')
	function modalDelete(self)
	{
		var id    = $(self).attr('data-id');
		var modal = $('#modal-delete');
		var url   = '{{ route("dashboard.user.destroy", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.find('#modal-delete-user').html('('+$(self).attr('data-name')+')');
		modal.modal('show');
	}
	@endcan
</script>
@endsection