routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.post.index');
// });

Auth::routes(['register' => false]);

// frontend
Route::get('/404', function(){
	return view('frontend.errors.404');
})->name('error.404');

Route::get('/', [App\Http\Controllers\Frontend\PostController::class, 'index'])->name('post.index');
Route::get('/pages/{slug}', [App\Http\Controllers\Frontend\PageController::class, 'show'])->name('page.show');
Route::get('/category/{id}', [App\Http\Controllers\Frontend\CategoryController::class, 'show'])->name('category.show');
Route::post('/newsletter', [App\Http\Controllers\Frontend\NewsletterController::class, 'store'])->name('newsletter.store');
Route::resource('/author', App\Http\Controllers\Frontend\AuthorController::class, ['names' => 'author'])->only('index', 'show');
Route::resource('/contact-us', App\Http\Controllers\Frontend\ContactUsController::class, ['names' => 'contact'])->only('index', 'store');
Route::post('/comment', [App\Http\Controllers\Frontend\CommentController::class, 'store'])->name('comment.store');

// backend
Route::group(['as' => 'dashboard.', 'prefix' => 'dashboard', 'middleware' => ['auth']], function (){
	Route::get('/', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('index');
	Route::resource('/posts', App\Http\Controllers\Backend\PostController::class, ['names' => 'post'])->except('show');
	Route::post('/posts/upload', [App\Http\Controllers\Backend\PostController::class, 'upload'])->name('post.upload');
	Route::resource('/categories', App\Http\Controllers\Backend\CategoryController::class, ['names' => 'category'])->except('create', 'edit', 'show');
	Route::resource('/message', App\Http\Controllers\Backend\MessageController::class, ['names' => 'message'])->only('index', 'destroy');
	Route::resource('/newsletter', App\Http\Controllers\Backend\NewsletterController::class, ['names' => 'newsletter'])->only('index', 'destroy');
	Route::resource('/comment', App\Http\Controllers\Backend\CommentController::class, ['names' => 'comment']);
	Route::post('/comment/reply', [App\Http\Controllers\Backend\CommentController::class, 'reply'])->name('comment.reply');
	Route::resource('/role', App\Http\Controllers\Backend\RoleController::class, ['names' => 'role'])->except('create', 'edit', 'show');
	Route::resource('/user', App\Http\Controllers\Backend\UserController::class, ['names' => 'user'])->except('create', 'edit', 'show');
	Route::put('/reset-password/{id}', [App\Http\Controllers\Backend\UserController::class, 'resetPassword'])->name('user.reset-password');
	Route::put('/setting/change-password', [App\Http\Controllers\Backend\SettingController::class, 'changePassword'])->name('setting.change-password');
	Route::resource('/setting', App\Http\Controllers\Backend\SettingController::class, ['names' => 'setting'])->only('index', 'update');
	Route::resource('/pages', App\Http\Controllers\Backend\PageController::class, ['names' => 'page']);

	Route::get('/404', function(){
		return view('backend.errors.404');
	})->name('error.404');
});

// post
Route::get('/{slug}', [App\Http\Controllers\Frontend\PostController::class, 'show'])->name('post.show');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
	use HasFactory;

	protected $guarded = ['id'];

	public function post()
	{
		return $this->belongsTo(Post::class);
	}

	public function childrens()
	{
		return $this->hasMany(Comment::class, 'parent_id');
	}
	
	public function parent()
	{
		return $this->belongsTo(Comment::class, 'parent_id');
	}

	public function reply()
	{
		return $this->belongsTo(Comment::class, 'reply_to');
	}

	public function user()
	{
		return $this->belongsTo(Post::class, 'created_by');
	}
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view categories', ['only' => ['index']]);
        $this->middleware('permission:create categories', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit categories', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete categories', ['only' => ['destroy']]);
    }

    public function index()
    {
        $categories = Category::orderByDesc('created_at')->get();
        return view('backend.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['name' => 'required|unique:categories,name']);
        $category = Category::create(['name' => strip_tags($request->name)]);
        if ($category) {
            return redirect()->back()->with('success', 'category '.$category->name.' saved successfully');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        if ($category) {
            $request->validate(['name' => 'required|unique:categories,name,'.$category->id]);
            $upd = $category->update(['name' => strip_tags($request->name)]);
            if ($upd) {
                return redirect()->back()->with('success', 'category '.$category->name.' updated successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if ($category) {
            $delete = $category->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'category '.$category->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view comments', ['only' => ['index']]);
        $this->middleware('permission:reply comments', ['only' => ['reply']]);
        $this->middleware('permission:delete comments', ['only' => ['destroy']]);
    }

    public function index()
    {
        $comments = Comment::has('post')->with('post', 'childrens.parent')->whereNull("parent_id")->orderByDesc('created_at')->get();
        return view('backend.comments.index', compact('comments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);
        if ($comment) {
            $delete = $comment->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'comment '.$comment->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }

    public function reply(Request $request)
    {
        $request->validate([
            'post_id'   => 'required|exists:posts,id',
            'parent_id' => 'required|exists:comments,id',
            'reply_to'  => 'required|exists:comments,id',
            'comment'   => 'required'
        ]);
        $user = auth()->user();
        $payloads = $request->except('_token');
        $payloads = removeHtmlTagsOfFields($payloads);
        $payloads['name']  = $user->name;
        $payloads['email'] = $user->email;
        $comment = Comment::create($payloads);
        if ($comment) {
            return redirect()->back()->with('success', 'comment '.$comment->name.' reply successfully');
        }
        return redirect()->back()->with('error', 'failed, Try Again');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
	public function index()
	{
		$visits = DB::table('shetabit_visits')->where('method', 'GET')->whereBetween('created_at', [date("Y-m-d H:i:s", strtotime("-7 days")), date("Y-m-d H:i:s")])->get()->groupBy(function($item) {
			return date('Y-m-d', strtotime($item->created_at));
		});
		$count_posts = Post::where('type', 1)->count();
		$count_views = DB::table('shetabit_visits')->where('method', 'GET');
		$top_posts   = DB::select("SELECT p.title, COUNT(slug) as total FROM posts p INNER JOIN shetabit_visits v ON v.url LIKE CONCAT('%/', p.slug) GROUP BY slug ORDER BY total DESC limit 5;");
		return view('backend.dashboard', compact('visits', 'count_posts', 'count_views', 'top_posts'));
	}
}

app/Http/Controllers/Backend/MessageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ContactUs;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view messages', ['only' => ['index']]);
        $this->middleware('permission:delete messages', ['only' => ['destroy']]);
    }

    public function index()
    {
        $messages = ContactUs::orderByDesc('created_at')->get();
        return view('backend.messages.index', compact('messages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $message = ContactUs::find($id);
        if ($message) {
            $delete = $message->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'message '.$message->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

app/Http/Controllers/Backend/NewsletterController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Newsletter;

class NewsletterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('permission:view newsletters', ['only' => ['index']]);
        $this->middleware('permission:delete newsletters', ['only' => ['destroy']]);
    }

    public function index()
    {
        $newsletters = Newsletter::orderByDesc('created_at')->get();
        return view('backend.newsletters.index', compact('newsletters'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $newsletter = Newsletter::find($id);
        if ($newsletter) {
            $delete = $newsletter->delete();
            if ($delete) {
                return redirect()->back()->with('success', 'newsletter '.$newsletter->name.' deleted successfully');
            }
            return redirect()->back()->with('error', 'failed, Try Again');
        }
        return redirect()->route('dashboard.error.404');
    }
}

resources/views/backend/comments/index.blade.php
@extends('layouts.backend')
@section('title', 'AdminLTE 3 | Comment View')
@section('css')
<link rel="stylesheet" type="text/css" href="{{asset('css/backend/datatable.css')}}">
<style type="text/css">
	#tbl-posts_paginate, #tbl-posts_filter{
		float: right;
	}
</style>
@endsection
@section('content')
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">DataTable comments</h3>
					</div>
					<div class="card-body">
						<table id="tbl-comment" class="table table-bordered table-hover dataTable">
							<thead>
								<th width="5%"><center>No</center></th>
								<th>Name</th>
								<th>Email</th>
								<th width="40%">Comment</th>
								<th>Post Title</th>
								<th width="10%"><center>#</center></th>
							</thead>
							<tbody>
								@foreach($comments as $comment)
								<tr>
									<td rowspan="{{$comment->childrens->count() + 1}}">{{$loop->iteration}}</td>
									<td>{{$comment->name}}</td>
									<td>{{$comment->email}}</td>
									<td>{{$comment->comment}}</td>
									<td>{{$comment->post->title ?? ''}}</td>
									<td>
										<center>
											@can('reply comments')
											<button type="button" class="btn btn-xs btn-outline-primary" data-parent_id="{{empty($comment->parent_id) ? $comment->id : $comment->parent_id}}" data-reply="{{$comment->id}}" data-title="{{$comment->post->title ?? ''}}" data-comment="{{$comment->comment}}" data-post_id="{{$comment->post->id ?? ''}}" onclick="modalReply(this)"><i class="fa fa-reply"></i></button>
											&nbsp;
											@endcan
											@can('delete comments')
											<button class="btn btn-xs btn-outline-danger" onclick="modalDelete(this)" data-id="{{$comment->id}}" data-name="{{$comment->email}}" type="button"><i class="fa fa-trash"></i></button>
											&nbsp;
											@endcan
											<a class="btn btn-xs btn-outline-info" href="{{route('post.show', $comment->post->slug).'#comment-'.$comment->id}}" target="_blank"><i class="fa fa-eye"></i></a>
										</center>
									</td>
								</tr>
								@foreach($comment->childrens as $children)
								<tr class="text-primary">
									<td class="d-none">#</td>
									<td>{{$children->name}}</td>
									<td>{{$children->email}}</td>
									<td>{{$children->comment}}</td>
									<td>Replyed To : {{$children->parent->name ?? ''}}</td>
									<td>
										<center>
											@can('reply comments')
											<button type="button" class="btn btn-xs btn-outline-primary" data-parent_id="{{empty($children->parent_id) ? $children->id : $children->parent_id}}" data-reply="{{$children->id}}" data-title="{{$children->post->title ?? ''}}" data-comment="{{$children->comment}}" data-post_id="{{$children->post->id ?? ''}}" onclick="modalReply(this)"><i class="fa fa-reply"></i></button>
											&nbsp;
											@endcan
											@can('delete comments')
											<button class="btn btn-xs btn-outline-danger" onclick="modalDelete(this)" data-id="{{$children->id}}" data-name="{{$children->email}}" type="button"><i class="fa fa-trash"></i></button>
											&nbsp;
											@endcan
											<a class="btn btn-xs btn-outline-info" href="{{route('post.show', $children->post->slug).'#comment-'.$children->id}}" target="_blank"><i class="fa fa-eye"></i></a>
										</center>
									</td>
								</tr>
								@endforeach
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@can('reply comments')
<div class="modal fade" id="modal-reply" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action="{{route('dashboard.comment.reply')}}" method="POST">
				@csrf
				<input type="hidden" name="post_id">
				<input type="hidden" name="parent_id">
				<input type="hidden" name="reply_to">
				<div class="modal-header bg-primary">
					<h4 class="modal-title">Reply comment</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form group">
						<label>Title</label>
						<input type="text" class="form-control" disabled id="reply-title">
					</div>
					<div class="form group">
						<label>Comment</label>
						<textarea class="form-control" rows="3" id="reply-comment" disabled></textarea>
					</div>
					<div class="form group">
						<label>Reply</label>
						<textarea class="form-control" rows="3" name="comment" required></textarea>
					</div>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan
@can('delete comments')
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="" method="POST">
				@csrf
				@method('DELETE')
				<div class="modal-header bg-danger">
					<h4 class="modal-title">Delete comment</h4>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="$(this).parents('.modal').modal('hide')">
						<span aria-hidden="true">×</span>
					</button>
				</div>
				<div class="modal-body">
					<p>Are you sure delete comment <b id="modal-delete-comment"></b></p>
				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-outline-light" data-dismiss="modal" onclick="$(this).parents('.modal').modal('hide')">Close</button>
					<button type="submit" class="btn btn-danger">Delete</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endcan
@endsection
@section('js')
<script type="text/javascript" src="{{asset('js/backend/datatable.js')}}"></script>
<script type="text/javascript">
	$(document).ready( function () {
		$('#tbl-comment').DataTable({
			"ordering": false
		});
	});
	
	@can('reply comments')
	function modalReply(self)
	{
		var modal     = $('#modal-reply');
		var parent_id = $(self).data('parent_id');
		var reply 	  = $(self).data('reply');
		var title     = $(self).data('title');
		var comment   = $(self).data('comment');
		var post_id   = $(self).data('post_id');

		$('input[name="post_id"]').val(post_id);
		$('input[name="parent_id"]').val(parent_id);
		$('input[name="comment"]').val(comment);
		$('input[name="reply_to"]').val(reply);
		$('#reply-comment').val(comment);
		$('#reply-title').val(title);
		modal.modal('show');
	}
	@endcan

	@can('delete comments')
	function modalDelete(self)
	{
		var id    = $(self).attr('data-id');
		var modal = $('#modal-delete');
		var url   = '{{ route("dashboard.comment.destroy", ":id") }}';
		url = url.replace(':id', id);
		modal.find('form').attr('action', url);
		modal.find('#modal-delete-comment').html('('+$(self).attr('data-name')+')');
		modal.modal('show');
	}
	@endcan
</script>
@endsection